site_name: Ноль Смертей
site_url: https://xn--e1aamffehtgn9h.xn--p1ai/

theme:
  name: material
  features:
    - navigation.sections

repo_name: NikiN2/VisionZero
repo_url: https://github.com/NikiN2/VisionZero
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - footnotes



nav:
  - 'Что такое Vision Zero' : 'index.md'
  - 'Типовые решения в инфраструктуре':
    - 'Тротуары': 'typical_solutions.md'
    - 'Проезжая часть' : 'typical_solutions.md'
    - 'Велодорожки' : 'typical_solutions.md'
    - 'Методы успокоения трафика' : 'typical_solutions.md'
    - 'Вертикальные неровности' : 'typical_solutions.md'
    - 'Горизонтальные неровности' : 'typical_solutions.md'
    - 'Разделение встречных потоков' : 'typical_solutions.md'
    - 'Общественный транспорт' : 'typical_solutions.md'
    - 'Безопасный двор' : 'typical_solutions.md'
  - 'Ответы на частые вопросы по VisionZero': 'faq.md'
  - 'Мифы и заблуждения' :   'myth.md'
  - 'Что добавить на сайт?' : 'CONTRIBUTING.md'
  - 'Обратная связь (ТГ канал/чат)' : 'feedback.md'

google_analytics:
  - G-30J52XFP29
  - auto

site_dir: _site