site_name: Ноль Смертей
site_url: https://нольсмертей.рф/
nav:
    - Что такое Vision Zero: index.md
    - Типовые решения в инфраструктуре: typical_solutions.md
    - Ответы на частые вопросы по VisionZero: faq.md
    - Мифы и заблуждения:   myth.md
    - Что добавить на сайт?: feedback.md
    - Обратная связь (ТГ канал/чат): feedback.md

theme:
    name: material

