site_name: Vision Zero
site_url: http://127.0.0.1:8000/
nav:
    - Начало: index.md
    - Что такое Vision Zero: about.md
    - Типовые решения в инфраструктуре: typical_solutions.md
    - Ответы на частые вопросы по VisionZero: faq.md
    - Мифы и заблуждения:   muth.md
    - Что добавить на сайт?: feedback.md
    - Обратная связь (ТГ канал/чат): feedback.md

theme:
  name: gitbook
