site_name: Vision Zero
site_url: https://nikin2.github.io/VisionZero/
nav:
    - Начало: index.md


theme:
    name: mkdocs
    locale: ru
    highlightjs: false
    nav_style: dark
    hljs_languages:
        - yaml
        - rust
