name: Push content to the user's GitHub pages repository

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material
#    - name: Make output folder
#      run: mkdir output
#    - name: Clone master branch
#      run: git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git" --branch master --single-branch
    - name: Generate static pages
      run: mkdocs build
    - name: Set git config and add changes
      run: |
          echo "xn--e1aamffehtgn9h.xn--p1ai" > ./CNAME
      working-directory: ./_site

    - name: Set yandex webmaster
      run: |
          echo '''<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>Verification: d9110b356dd8f81b</body></html>''' > ./yandex_d9110b356dd8f81b.html
      working-directory: ./_site

    - name: Deploy site to gh-pages branch
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.GH_PAT }}
#    - name: Push and send notification
#      run: |
#          COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
#          git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
#          git commit -m "${COMMIT_MESSAGE}"
#          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git gh-pages
#          curl "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage?text=$COMMIT_MESSAGE %0ALook at ${GITHUB_ACTOR}.github.io %0ARepository%3A github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io&chat_id=${{ secrets.ADMIN_ID }}"
#      working-directory: ./site